// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerdDiplom.Context;

#nullable disable

namespace ServerdDiplom.Migrations
{
    [DbContext(typeof(DiplomDbContext))]
    [Migration("20240510143655_mg3")]
    partial class mg3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerdDiplom.Data.ComissionNumber", b =>
                {
                    b.Property<string>("ComissionNumberValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UniversityName1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ComissionNumberValue");

                    b.HasIndex("UniversityName1");

                    b.ToTable("ComissionsNumber");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Exams", b =>
                {
                    b.Property<string>("Exams_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Exams_Name");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Faculty", b =>
                {
                    b.Property<string>("FacultyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FacultyName");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("ServerdDiplom.Data.PassingScoreDayFreeFM", b =>
                {
                    b.Property<int>("ScoreFreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreFreeId"));

                    b.Property<int>("PassingScoreValueDayForMoney")
                        .HasColumnType("int");

                    b.Property<int>("PassingScoreValueDayFree")
                        .HasColumnType("int");

                    b.HasKey("ScoreFreeId");

                    b.ToTable("PassingScoreDayFreeFMs");
                });

            modelBuilder.Entity("ServerdDiplom.Data.PassingScoreExtramuralFreeFM", b =>
                {
                    b.Property<int>("ScoreForMoneyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreForMoneyId"));

                    b.Property<int>("PassingScoreValueExtramuralForMoney")
                        .HasColumnType("int");

                    b.Property<int>("PassingScoreValueExtramuralFree")
                        .HasColumnType("int");

                    b.HasKey("ScoreForMoneyId");

                    b.ToTable("PassingScoreExtramuralFreeFMs");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Regions", b =>
                {
                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Region");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality", b =>
                {
                    b.Property<string>("SpecialityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("Trainin_Period")
                        .HasColumnType("real");

                    b.Property<float>("TrainingPeriodValue")
                        .HasColumnType("real");

                    b.HasKey("SpecialityName");

                    b.HasIndex("TrainingPeriodValue");

                    b.ToTable("Speciality");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_Exams", b =>
                {
                    b.Property<string>("SpecialityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExamsId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecialityId", "ExamsId");

                    b.HasIndex("ExamsId");

                    b.ToTable("Speciality_Exams");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_Faculty", b =>
                {
                    b.Property<string>("SpecialityNameId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacultyNameId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpecialityName")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SpecialityNameId", "FacultyNameId");

                    b.HasIndex("FacultyName");

                    b.HasIndex("SpecialityName");

                    b.ToTable("Speciality_Faculties");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_PassingScoreForMoney", b =>
                {
                    b.Property<string>("SpecialityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ScoreForMoneyId")
                        .HasColumnType("int");

                    b.HasKey("SpecialityId", "ScoreForMoneyId");

                    b.HasIndex("ScoreForMoneyId");

                    b.ToTable("Speciality_PassingScoreForMoney");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_PassingScoreFree", b =>
                {
                    b.Property<string>("SpecialityNameId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ScoreFreeId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialityName")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SpecialityNameId", "ScoreFreeId");

                    b.HasIndex("ScoreFreeId");

                    b.HasIndex("SpecialityName");

                    b.ToTable("Speciality_PassingScoreFrees");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Towns", b =>
                {
                    b.Property<string>("StreetName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionsNameRegion")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regions_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StreetName");

                    b.HasIndex("RegionsNameRegion");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("ServerdDiplom.Data.TrainingPeriod", b =>
                {
                    b.Property<float>("TrainingPeriodValue")
                        .HasColumnType("real");

                    b.HasKey("TrainingPeriodValue");

                    b.ToTable("TrainingPeriods");
                });

            modelBuilder.Entity("ServerdDiplom.Data.University", b =>
                {
                    b.Property<string>("UniversityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TownNameStreetName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Town_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniversityDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UniversityLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UniversityName");

                    b.HasIndex("TownNameStreetName");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("ServerdDiplom.Data.University_Faculty", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacultyId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UniversityId", "FacultyId");

                    b.HasIndex("FacultyId");

                    b.ToTable("University_Faculties");
                });

            modelBuilder.Entity("ServerdDiplom.Data.ComissionNumber", b =>
                {
                    b.HasOne("ServerdDiplom.Data.University", "University")
                        .WithMany("ComissionNumber")
                        .HasForeignKey("UniversityName1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality", b =>
                {
                    b.HasOne("ServerdDiplom.Data.TrainingPeriod", "TrainingPeriod")
                        .WithMany("Specialities")
                        .HasForeignKey("TrainingPeriodValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPeriod");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_Exams", b =>
                {
                    b.HasOne("ServerdDiplom.Data.Exams", null)
                        .WithMany("Speciality_Exams")
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerdDiplom.Data.Speciality", null)
                        .WithMany("Speciality_Exams")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_Faculty", b =>
                {
                    b.HasOne("ServerdDiplom.Data.Faculty", null)
                        .WithMany("Speciality_Faculties")
                        .HasForeignKey("FacultyName");

                    b.HasOne("ServerdDiplom.Data.Speciality", null)
                        .WithMany("Speciality_Faculties")
                        .HasForeignKey("SpecialityName");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_PassingScoreForMoney", b =>
                {
                    b.HasOne("ServerdDiplom.Data.PassingScoreExtramuralFreeFM", null)
                        .WithMany("Speciality_PassingScoreForMoney")
                        .HasForeignKey("ScoreForMoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerdDiplom.Data.Speciality", null)
                        .WithMany("Speciality_PassingScoreForMoney")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality_PassingScoreFree", b =>
                {
                    b.HasOne("ServerdDiplom.Data.PassingScoreDayFreeFM", null)
                        .WithMany("Speciality_PassingScoreFrees")
                        .HasForeignKey("ScoreFreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerdDiplom.Data.Speciality", null)
                        .WithMany("Speciality_PassingScoreFrees")
                        .HasForeignKey("SpecialityName");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Towns", b =>
                {
                    b.HasOne("ServerdDiplom.Data.Regions", "RegionsName")
                        .WithMany("Towns")
                        .HasForeignKey("RegionsNameRegion");

                    b.Navigation("RegionsName");
                });

            modelBuilder.Entity("ServerdDiplom.Data.University", b =>
                {
                    b.HasOne("ServerdDiplom.Data.Towns", "TownName")
                        .WithMany("Universities")
                        .HasForeignKey("TownNameStreetName");

                    b.Navigation("TownName");
                });

            modelBuilder.Entity("ServerdDiplom.Data.University_Faculty", b =>
                {
                    b.HasOne("ServerdDiplom.Data.Faculty", null)
                        .WithMany("University_Faculties")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerdDiplom.Data.University", null)
                        .WithMany("University_Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerdDiplom.Data.Exams", b =>
                {
                    b.Navigation("Speciality_Exams");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Faculty", b =>
                {
                    b.Navigation("Speciality_Faculties");

                    b.Navigation("University_Faculties");
                });

            modelBuilder.Entity("ServerdDiplom.Data.PassingScoreDayFreeFM", b =>
                {
                    b.Navigation("Speciality_PassingScoreFrees");
                });

            modelBuilder.Entity("ServerdDiplom.Data.PassingScoreExtramuralFreeFM", b =>
                {
                    b.Navigation("Speciality_PassingScoreForMoney");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Regions", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Speciality", b =>
                {
                    b.Navigation("Speciality_Exams");

                    b.Navigation("Speciality_Faculties");

                    b.Navigation("Speciality_PassingScoreForMoney");

                    b.Navigation("Speciality_PassingScoreFrees");
                });

            modelBuilder.Entity("ServerdDiplom.Data.Towns", b =>
                {
                    b.Navigation("Universities");
                });

            modelBuilder.Entity("ServerdDiplom.Data.TrainingPeriod", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("ServerdDiplom.Data.University", b =>
                {
                    b.Navigation("ComissionNumber");

                    b.Navigation("University_Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
